### ISSUE TITLE
Chronos\Date breaks DateTimeImmutable expected behaviour

### ISSUE THREAD

**Issue by nyamsprod** [cakephp/chronos#77] opened 2016-02-02 17:06 UTC
As the author of the [League\Period](http://period.thephpleague.com/) library, I tried to test the Chronos package against my library, which is a single PHP class, [League\Period\Period](https://github.com/thephpleague/period/blob/master/src/Period.php). I'm having a issue which the fact that `Chronos\Date` object extends `DateTimeImmutable` object.
### The issue

Here's a simple example:

The `Period` object has a method called [Period::split](http://period.thephpleague.com/api/properties/#periodsplit). This method enables exploding a `Period` object into smaller `Period` objects with a given duration. The method returns a PHP Generator.

Using `Chronos\Chronos`, I get the expected behavior:

``` php
use League\Period\Period;
use Chronos\Chronos;

$period = new Period(Chronos::yesterday(), Chronos::tomorrow());
$res = $period->split(new DateInterval('PT12H'));
foreach ($res as $innerPeriod) {
    //generate 4 small Period objects
    //whose datepoints are expressed as Chronos\Chronos objects
}
```

However, using `Chronos\Date`, I get an unexpected behavior:

``` php
use League\Period\Period;
use Chronos\Date;

$period = new Period(Date::yesterday(), Date::tomorrow());
$res = $period->split(new DateInterval('PT12H'));
foreach ($res as $innerPeriod) {
    //an infinite loop is created
    //each time a Period object with the same datepoints expressed as Chronos\Date objects
    //is created since the time part are "frozen" 
}
```
### The explanation

The keep the `Period` class immutable it must work with `DateTimeImmutable` objects. When given a `DateTimeImmutable` object, the object will be used as is and won't be converted into a proper `DateTimeImmutable` object. This is to ease using extended `DateTimeImmutable` object like `Chronos\Chronos`. 
### What to do ?

I do understand the goal behind `Chronos\Date` but IMHO it should not extends `DateTimeImmutable` otherwise you end up with an object which claims to follow a known object behavior but yet act differently. Any code that relies on `DateTimeImmutable` will face the same issue as long as `Chronos\Date` extends `DateTimeImmutable`. Unless all third parties code are force to make a distinction between `DateTimeImmutable` and `Chronos\Date` objects which would be rather strange. This does not necessary require `Chronos\Date` to not follow the `ChronosInterface`

**Comment by markstory** [comment] 2016-02-02 23:17
What kind of results would you expect if you split 'dates' into 12hr periods? It feels like a mismatch in intentions to me.

**Comment by josegonzalez** [comment] 2016-02-03 00:39
@nyamsprod what *should* that `\Cake\Chronos\Date` object extend? IIRC, there isn't a `\Date` class in PHP, so extending `DateTime*` and calling it `Date` to denote it's usage seems reasonable to me.

**Comment by nyamsprod** [comment] 2016-02-03 08:08
@markstory @josegonzalez The real issue is typehinting. Let's look at a simpler example:

```php
function doSomething(DateImmutable $datetime)
{
    return $dateime->add(new DateInterval('PT1H'));
}
```
I expect this function to only accepts `DateTimeImmutable` objects or objects extending it. And I expect the function to return me a `DateTimeImmutable` object or the object extending it with the added Interval because this is what `DateTimeImmutable::add` is supposed to do. 

`Cake\Chronos\Date` by extending `DateTimeImmutable` and not completely honoring `DateTimeImmutable::add` usage breaks code expectations.

This is the problem I tried to highlight with my previous example. Hope this simpler example is better understood.
 
@josegonzalez The real question should be Does `Cake\Chronos\Date` needs to extend anything to begin with ?

**Comment by josegonzalez** [comment] 2016-02-03 08:29
@nyamsprod We'd have to re-implement basically all of the DateTimeImmutable functionality in PHP to get what we'd need for the `Cake\Chronos\Date` functionality.

I agree that it sucks that a developer can misuse the functionality because they expected the `add` method to work like it does in `DateTimeImmutable`. In this case however, the specific class is working as intended/designed, as it is a `Date` class, not strictly a `DateTime` class.

Does your Period project work with `Cake\Chronos\Date` for periods that are defined in days? Just curious.

**Comment by nyamsprod** [comment] 2016-02-03 08:45
> Does your Period project work with Cake\Chronos\Date for periods that are defined in days? Just curious

@josegonzalez Yes it does but that's not the issue. 

The real issue is that currently **`Cake\Chronos\Date` pretends to be something it is not.** PHP's typehinting feature which is the root of any modern code is completely disregarded. It means that I can neither safely use nor recommend the library to anyone.

**Comment by josegonzalez** [comment] 2016-02-03 09:05
I think we can both agree that re-implementing 90% of the php `DateTime` class just so we can strip out the `Time` portion is undesirable - we're almost certainly going to have bugs, suffer from (maybe only slightly) worse performance, and not be able to make as many guarantees about functionality.

That said, given that we cannot otherwise detect this - since its a programmer error at run-time - I can see a few options:

- Remove the Date class completely. I don't think this is viable because it reduces functionality in this library (and personally think it's useful).
- Reimplement all of the necessary Date logic in pure php.
- Throw a RunTime exception when specified times are not zeroed out already.
- Instead of subclassing, use the facade-pattern to manipulate an instance of DateTime underneath, again ignoring times. 

Just curious, how did you come across this issue?

**Comment by nyamsprod** [comment] 2016-02-03 10:17
> Just curious, how did you come across this issue?

I use Period to generate some reporting using Cake\Chronos\Date seemed to fit my script logic. So for the time being I'll revert to using Cake\Chronos\Chronos

**Comment by josegonzalez** [comment] 2016-02-03 17:50
Which of the above options would you prefer we do? `ChronosInterface` exists so we can typecheck as to whether or not the object coming in is a type of Date/DateTime object from the Chronos package, and we would use a more specific typehint where necessary.

**Comment by nyamsprod** [comment] 2016-02-03 19:17
I would go with

> Instead of subclassing, use the facade-pattern to manipulate an instance of DateTime underneath, again ignoring times.

**Comment by josegonzalez** [comment] 2016-02-03 20:39
Awesome! Do you mind making a PR that implements this functionality?

**Comment by nyamsprod** [comment] 2016-02-04 12:11
@josegonzalez I have my hands full with other open source projects right now, I would otherwise, but thanks for the offer

**Comment by lorenzo** [comment] 2016-02-04 20:40
The Date class needs to extends DatetimeImmutable, since it cannot implement it by itself due to PHP language restrictions

**Comment by nyamsprod** [comment] 2016-02-04 21:39
@lorenzo I'll quote [Cake's documentation on Chronos](http://book.cakephp.org/3.0/en/chronos.html#date-objects):

> PHP only provides a single DateTime object. Representing calendar dates can be a bit awkward with this class as it includes timezones, and time components that don’t really belong in the concept of a ‘day’. Chronos provides a Date object that allows you to represent dates. 

As you can see, the documentation goes as far as explaining why it is a bad idea to use a DateTime object to represent a day. So, if I were to follow the documentation intent I would expect the `Date` and the `MutableDate` classes to not implement the `DateTimeInterface` as this interface and its implementations in PHP `DateTime` and `DateTimeImmutable`.

**Comment by odan** [comment] 2018-07-23 13:04
Today I've got the issue. IMHO it's very dangerous to use the `\Cake\Chronos\Date` class because the interface pretends something it does not do.

```php
// 1. Test with DateTimeImmutable
$time = new DateTimeImmutable('2018-01-01 15:20:45');

$dateTime1 = $time->setTime(0, 0, 0);
$dateTime2 = $time->setTime(23, 59, 59);

echo_date_time($dateTime1); // 2018-01-01 00:00:00
echo_date_time($dateTime2); // 2018-01-01 23:59:59

// 2. Test with Chronos Date
$chronosDate = new \Cake\Chronos\Date('2018-01-01 15:20:45');

$chronosDateDateTime1 = $chronosDate->setTime(0, 0, 0);
$chronosDateDateTime2 = $chronosDate->setTime(23, 59, 59);

echo_date_time($chronosDateDateTime1); // 2018-01-01 00:00:00
echo_date_time($chronosDateDateTime2); // 2018-01-01 00:00:00 -> What?!

// helper
function echo_date_time(DateTimeImmutable $dateTime) {
	echo $dateTime->format('Y-m-d H:i:s') . "\n";
}
```

**Comment by ravage84** [comment] 2018-07-23 13:07
Can't we throw an exeption if one tries to set a time on a Chronos\Date object? This could prevent many hidden and hard to find bugs.

**Comment by markstory** [comment] 2018-07-23 14:35
@odan I can see how its confusing. But setting 'time' on a calendar date (which is what `Date` is intended for) is a strange operation.

@ravage84 We might be able to raise exceptions, but I don't know how that will work with PHP's internal usage of datetime objects.

**Comment by ravage84** [comment] 2018-07-23 17:07
> @odan I can see how its confusing. But setting 'time' on a calendar date (which is what Date is intended for) is a strange operation.

@markstory It's strange that a "presumed" Date object provides an API for manipulating the time. I see why it was designed like this, but I guess the actual source of the problem is that PHP does not have dedicated Date interface... Everything else is just a consequence of that.

> @ravage84 We might be able to raise exceptions, but I don't know how that will work with PHP's internal usage of datetime objects.

Well, the only alternative is to put a big fat warning on using the class wherever sensible - which will most certainly overlooked by many, nonetheless.

**Comment by nyamsprod** [comment] 2018-07-23 17:41
@markstory the real issue is that a Date and a DateTime are two distinct concepts so the Chronos Date object should had have its own interface and provide converter method to generate or create new instance from the PHP interface

**Comment by markstory** [comment] 2018-07-23 18:40
@nyamsprod Fair. Had I known now what I know now that would have likely been a path I would have gone down. At the time, making a mutant `DateTime` appeared to be a simple way to introduce calendar dates without breaking a significant amount of consuming code.

**Comment by othercorey** [comment] 2019-11-16 06:14
Would the solution here here be to throw an exception when a non-Date compatible part of DateTimeImmutable is used instead of suppressing the result?

This code below feels invalid and undefined behavior.
```
$period = new Period(Date::yesterday(), Date::tomorrow());
$res = $period->split(new DateInterval('PT12H'));
```

**Comment by nyamsprod** [comment] 2019-11-16 08:44
@othercorey the code is perfectly fine and valid according to DatimeImmutable documentation 😉. And afaik, for interoperability that's what matters otherwise there's no need to make Date extending the PHP class.

**Comment by othercorey** [comment] 2019-11-16 10:02
> @othercorey the code is perfectly fine and valid according to DatimeImmutable documentation 😉. And afaik, for interoperability that's what matters otherwise there's no need to make Date extending the PHP class.

It goes against stated Date documentation though that Date is re-interpreted as a calendar date.

**Comment by nyamsprod** [comment] 2019-11-16 10:06
@othercorey then Date should not extends DateTime/Immutable and I would fully agree with you

**Comment by othercorey** [comment] 2019-11-16 10:13
> @othercorey then Date should not extends DateTime/Immutable and I would fully agree with you

Regardless of how it is implemented.  That is simply how Date works.  If we changed Date to not extend DateTime, then this wouldn't generated valid Period's either.  I don't think that use case would be supported.

**Comment by othercorey** [comment] 2019-11-16 10:19
Closing as this really isn't going to change with the current Date implementation.  If Date is changed to be free-standing then this also goes away without a special API to generate periods.

**Closed by othercorey** 2019-11-16 10:19 UTC
Labels: bug
