### ISSUE TITLE
Handling of the year before 1970

### ISSUE THREAD

**Issue by tokyo-walker** [cakephp/chronos#287] opened 2021-03-10 12:33 UTC
If I get the year before 1970 years will add 100 years

```
new Chronos('1969-01-01'))->year // 2069
```

Can't convert to the correct number of years?

**Comment by othercorey** [comment] 2021-03-10 14:14
What version of Chronos are you using?

Do you set a locale?

**Comment by sasaki-yourmystar** [comment] 2021-03-12 02:42
I use version `1.2.3`.
I don't set a locale.

**Comment by tokyo-walker** [comment] 2021-03-12 02:43
I use version `1.2.3`.
I don't set a locale.

**Comment by markstory** [comment] 2021-03-13 02:08
I'm not able to reproduce the results you're having in a test application I have locally.

```php
ᐉ bin/cake console
You can exit with `CTRL-C` or `exit`

Psy Shell v0.10.6 (PHP 7.4.9 — cli) by Justin Hileman
>>> \Cake\Core\Configure::version()
=> "4.2.4"
>>> $d = new Cake\Chronos\Chronos('1968-01-01');
=> Cake\Chronos\Chronos @-63158400 {#2609
     hasFixedNow: false,
     time: "1968-01-01 00:00:00.000000",
     date: 1968-01-01 00:00:00.0 UTC (+00:00),
   }
>>> $d->year;
=> 1968
```

**Comment by garas** [comment] 2021-03-13 11:22
Is your snippet complete, is these some additional step? There is double closing parenthesis.
```
new Chronos('1969-01-01'))->year // 2069
                         ^
```

Behavior to add 100 years to year before 70 exists when parsing two digits year like '69-01-01'.

**Comment by tokyo-walker** [comment] 2021-03-22 06:23
I'm sorry. It will be here correctly
```
$year = (new Chronos('1969-01-01'))->year // 2069
```

> Behavior to add 100 years to year before 70 exists when parsing two digits year like '69-01-01'.

Okay, I understand. I'll execute by four digits.

**Closed** 2021-03-22 06:50 UTC
Labels: question
