### ISSUE TITLE
Error: debugInfo must return an array

### ISSUE THREAD

**Issue by hktr92** [cakephp/chronos#164] opened 2018-03-19 14:34 UTC
Hello, there.

While debugging with phpstorm and xdebug the behavior of a controller which uploads avatar images, I came across an error thrown by PHP:
![image](https://user-images.githubusercontent.com/7689151/37600954-7c9960b0-2b91-11e8-8391-489cdc185347.png)

I think that it's related to #129 which introduced the given method. 
It's a Symfony 4-based project and for dev environment, I'm using PHP 7.1.15 with Xdebug 2.6.0. Tried an `composer update cakephp/chronos`, but still fails.

What can be done to fix the encountered issue?

**Comment by markstory** [comment] 2018-03-19 14:41
But it does return an array https://github.com/cakephp/chronos/blob/be20ca1679c532556c9abec67f230273bc874ef4/src/Chronos.php#L136-L144

**Comment by hktr92** [comment] 2018-03-19 15:50
Created a new directory, ran `composer req cakephp\chronos`, instantiated the class, stepped into and xdebug died. Removed the timezone line from array, stepped into and it worked, but with each step over, i got this error(s) in console:

    /usr/bin/php7.1 -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 /home/hktr92/Playground/xdebug-crash/exec.php                                       
    PHP Warning:  DateTimeImmutable::getTimezone(): The DateTime object has not been correctly initialized by its constructor in /home/hktr92/Playground/xdebug-crash/vendor/cakephp/chronos/src/Chronos.php on lin
    PHP Stack trace:                                                                                                                                                                                               
    PHP   1. {main}() /home/hktr92/Playground/xdebug-crash/exec.php:0                                                                                                                                              
    PHP   2. Cake\Chronos\Chronos->__construct($time = *uninitialized*, $tz = *uninitialized*) /home/hktr92/Playground/xdebug-crash/exec.php:8                                                                     
    PHP   3. Cake\Chronos\Chronos->__debugInfo() /home/hktr92/Playground/xdebug-crash/vendor/cakephp/chronos/src/Chronos.php:80                                                                                    
    PHP   4. Cake\Chronos\Chronos->getTimezone() /home/hktr92/Playground/xdebug-crash/vendor/cakephp/chronos/src/Chronos.php:169                                                                                   
    PHP Warning:  DateTimeImmutable::format(): The DateTime object has not been correctly initialized by its constructor in /home/hktr92/Playground/xdebug-crash/vendor/cakephp/chronos/src/Chronos.php on line 172

Then, I added the null coalescence test on `$this->getTimezone()` and I could step into class constructor, but the errors kept showing up:
```php
    public function __debugInfo()
    {
        $properties = [
            'time' => $this->format('Y-m-d H:i:s.u'),
            'timezone' => $this->getTimezone() ?? $this->getTimezone()->getName(),
            'hasFixedNow' => isset(self::$testNow)
        ];

        return $properties;
    }
```

**Comment by markstory** [comment] 2018-03-19 21:02
That warning is likely coming out of php internals. You might be able to get around that warning if the `timezone` is omitted from the debug data entirely.

**Comment by odan** [comment] 2018-03-28 14:22
This is the default behavior of PHP. 

> __debugInfo - This method is called by var_dump() when dumping an object to get the properties that should be shown. If the method isn't defined on an object, then all public, protected and private properties will be shown.

[Source](http://php.net/manual/en/language.oop5.magic.php#object.debuginfo)

When you try to inspect a variable with Xdebug, the magic method `__debugInfo()` is called automatically because Xdebug tries to load the state via `var_dump()`. If the internal state of your object is not initialized (depends on the breakpoint), you receive this error.

Using `__debugInfo` is a problem for all XDebug users because it causes many problems and unwanted side effects (like the database lastInsertId bug). I hope the CakePHP team will soon remove the `__debugInfo()` method everywhere in the code base.

**Comment by odan** [comment] 2019-02-06 21:21
Today I've had the same issue with Xdebug. Xdebug make use of the magic `__debugInfo()` method to fetch the object details. Depending on the line you set an Xdebug breakpoint the `__debugInfo` method is getting called, even before the `Chronos` object is fully initialized by the constructor.

Setting the Xdebug breakpoint here will trigger `__debugInfo()`, even before the Chronos constructor is finished.

![image](https://user-images.githubusercontent.com/781074/52372768-420b3f00-2a59-11e9-925f-9f479981013b.png)

But this is not the only problematic breakpoint. Even in a line like this the object cannot be fully initialized by the Chronos constructor, example:

![image](https://user-images.githubusercontent.com/781074/52374224-03778380-2a5d-11e9-990e-9fdcac58b90c.png)

This makes it very hard for me to debug in real life because I have to restart Apache every time.

Possible Error message: 

* `Warning: DateTimeImmutable::format(): The DateTime object has not been correctly initialized by its constructor in vendor\cakephp\chronos\src\Chronos.php on line 195`
* `Warning: DateTimeImmutable::getTimezone(): The DateTime object has not been correctly initialized by its constructor`

This error is throw in the  `__debugInfo` method, line 194 in Chronos.php.

![image](https://user-images.githubusercontent.com/781074/52372904-9b736e00-2a59-11e9-8951-025b78e11324.png)

The reason ist, that in this moment the object has no time and timezone set.

![image](https://user-images.githubusercontent.com/781074/52372986-daa1bf00-2a59-11e9-966a-3c6584131b7d.png)

The problem is, that the current `__debugInfo()` works only for fully a initialized Chrono object. Here is an example of a working `Chronos `object:

![image](https://user-images.githubusercontent.com/781074/52372539-b8f40800-2a58-11e9-89b0-92e2769e829b.png)

You can see there is a `date`, `timezone` and `timezone_type` property now.

A possible and simple fix would be to make `__debugInfo()` more flexible.

Current code (buggy with xdebug):

```php
public function __debugInfo()
{
    $properties = [
        'time' => $this->format('Y-m-d H:i:s.u'),
        'timezone' => $this->getTimezone()->getName(),
        'hasFixedNow' => self::hasTestNow()
    ];

    return $properties;
}
```

New fixed code:

```php
public function __debugInfo()
{
    if (!property_exists($this, 'date') || !property_exists($this, 'timezone')) {
        // The object has not been correctly initialized by its constructor
        return [
            'time' => '',
            'timezone' => '',
            'hasFixedNow' => self::hasTestNow(),
        ];
    }

    $properties = [
        'time' => $this->format('Y-m-d H:i:s.u'),
        'timezone' => $this->getTimezone()->getName(),
        'hasFixedNow' => self::hasTestNow()
    ];

    return $properties;
}
```

Tested with PHP 7.0 and PHP 7.3. Would it be possible to add this fix? I really need a fix for this issue.

**Comment by markstory** [comment] 2019-02-06 21:48
> Would it be possible to add this fix? I really need a fix for this issue.

The proposed changes seem reasonable to me.

**Comment by dereuromark** [comment] 2019-02-06 21:56
why not null instead of empty string? otherwise I would also agree here.

**Comment by odan** [comment] 2019-02-06 22:20
With `null`, it would work too. It don't has to be an empty string.

```php
if (!property_exists($this, 'date') || !property_exists($this, 'timezone')) {
    // The object has not been correctly initialized by its constructor
    return [
        'time' => null,
        'timezone' => null,
        'hasFixedNow' => self::hasTestNow(),
    ];
}

//...
```

**Comment by odan** [comment] 2019-02-07 08:22
PS: The [Cake\I18n\DateFormatTrait.php](https://github.com/cakephp/cakephp/blob/master/src/I18n/DateFormatTrait.php#L436) class needs this fix too:

```php
public function __debugInfo()
{
    if (!property_exists($this, 'date') || !property_exists($this, 'timezone')) {
        // The object has not been correctly initialized by its constructor
        return [
            'time' => null,
            'timezone' => null,
            'hasFixedNow' => self::hasTestNow(),
        ];
    }

    return [
        'time' => $this->toIso8601String(),
        'timezone' => $this->getTimezone()->getName(),
        'fixedNowTime' => static::hasTestNow() ? static::getTestNow()->toIso8601String() : false
    ];
}
```

**Comment by garas** [comment] 2019-02-07 10:53
As properties do not exist yet, it should return only `['hasFixedNow' => ...]`

**Comment by odan** [comment] 2019-02-07 12:26
> As properties do not exist yet, it should return only `['hasFixedNow' `

I agree and updated the fixes.

**Comment by markstory** [comment] 2019-02-07 14:57
@odan Sounds like you have a lot of context and interest in fixing this problem, would you be willing to send a pull request for these changes?

**Comment by odan** [comment] 2019-02-07 20:53
@markstory Ok I will try it :-)

**Comment by dereuromark** [comment] 2019-02-10 13:50
PR open: https://github.com/cakephp/chronos/pull/188

**Closed by dereuromark** 2019-02-10 13:50 UTC
